ExtensionUUID
byndcloud/quoti-cli pull request #13
Opened 2022-01-18 18:08 UTC by luizAlbuquerqueJr

TASK: https://www.notion.so/beyondco/Marketplace-A-instala-o-de-extens-es-s-funciona-nas-ORGs-se-tiverem-o-mesmo-ID-da-extens-o-quando-0c4826f748334203960d07ee4d4fcdf1

2022-01-19 00:26 UTC, nmf2 requested changes
Mudanças pontuais e simples.

2022-01-19 00:26 UTC, nmf2 commented on src/commands/publish.js
> +      }
É mais seguro fazer um `!manifest.extensionUUID`, vai que é undefined ou null?

2022-01-19 00:26 UTC, nmf2 commented on src/commands/serve.js
> +            if (manifest.extensionUUID === '') {
É mais seguro fazer um `!manifest.extensionUUID` na checagem do if, vai que é undefined ou null?

2022-01-19 00:26 UTC, nmf2 commented on src/services/extension.js
> +const { v4: uuidv4 } = require('uuid')
Não usar esse package, usar a função `randomUUID` do package [crypto](https://nodejs.org/api/crypto.html#cryptorandomuuidoptions), é um package padrão do node, não precisa instalar é só importar (tipo o `fs`)

2022-01-19 00:26 UTC, nmf2 commented on src/services/extension.js
> +    if (this.manifest.extensionUUID === '') {
É mais seguro fazer um `!manifest.extensionUUID` na checagem do if, vai que é undefined ou null?

2022-01-19 11:36 UTC, luizAlbuquerqueJr commented on src/commands/publish.js
> +      }
done

2022-01-19 11:36 UTC, luizAlbuquerqueJr commented on src/commands/serve.js
> +            if (manifest.extensionUUID === '') {
done

2022-01-19 11:36 UTC, luizAlbuquerqueJr commented on src/services/extension.js
> +const { v4: uuidv4 } = require('uuid')
done

2022-01-19 11:36 UTC, luizAlbuquerqueJr commented on src/services/extension.js
> +    if (this.manifest.extensionUUID === '') {
done

2022-01-24 14:19 UTC, nmf2 approved these changes
LGTM!
<img src="https://media3.giphy.com/media/tsoavY9gOiXmInKD4B/giphy.gif"/>

2022-01-24 14:20 UTC, merged