Corrigindo o uso do spinner
byndcloud/quoti-cli pull request #16
Opened 2022-01-31 20:24 UTC by luizAlbuquerqueJr

Essa P.R tem como objetivo a correção do fluxo de uso do spinner.  Não tem task no Notion

2022-02-01 15:28 UTC, nmf2 requested changes
Pequena mudança

2022-02-01 15:28 UTC, nmf2 commented on src/commands/serve.js
> +          await extensionService.upload(fileBuffer, this.getUploadFileName(manifest))
@luizAlbuquerqueJr, A gente não deve usar o await aqui, o qt serve deve ser usado primariamente só com o websocket e esse upload é só um fallback, não queremos que o usuário tenha que esperar o upload pra poder enviar o código pro front pelo socket (que é feito abaixo).

Tenta manter em mente fazer alterações só pertinentes à task na PR, por favor?

```suggestion
          extensionService.upload(fileBuffer, this.getUploadFileName(manifest))
```

2022-02-01 15:38 UTC, nmf2 commented on src/services/extension.js
> +    this.spinner.start(`Fazendo da extensão ${this.manifest.name} upload...`)
```suggestion
    this.spinner.start(`Fazendo upload da extensão ${this.manifest.name}...`)
```

2022-02-01 15:39 UTC, nmf2 commented on src/commands/serve.js
> +const { CliUx } = require('@oclif/core')
@luizAlbuquerqueJr, esse reqire não é utilizado, né?
```suggestion
```

2022-02-01 16:50 UTC, luizAlbuquerqueJr commented on src/commands/serve.js
> +          await extensionService.upload(fileBuffer, this.getUploadFileName(manifest))
sabia que tinha algum truque nesse trecho de código. Irei remover o await deixa comigo.

2022-02-01 16:51 UTC, luizAlbuquerqueJr commented on src/commands/serve.js
> +const { CliUx } = require('@oclif/core')
boa observação

2022-02-02 16:40 UTC, nmf2 commented on src/commands/serve.js
> +          await extensionService.upload(fileBuffer, this.getUploadFileName(manifest))
You da man 
<img src="https://media4.giphy.com/media/3oEdv6sy3ulljPMGdy/giphy.gif"/>

2022-02-02 16:41 UTC, nmf2 commented on src/commands/serve.js
> +const { CliUx } = require('@oclif/core')
<img src="https://media4.giphy.com/media/RKw94AILIkuWY/giphy.gif"/>

2022-02-02 16:42 UTC, nmf2 approved these changes
LGTM!
<img src="https://media1.giphy.com/media/Prquorv3BhAmFeiNo2/giphy.gif"/>

2022-02-02 16:42 UTC, merged