Permite deploy de qualquer diretório
byndcloud/quoti-cli pull request #21
Opened 2022-02-03 15:12 UTC by luizAlbuquerqueJr

https://www.notion.so/beyondco/Fazer-deploy-de-qualquer-diret-rio-3c435e22fb044fa099901b74b1c71692

2022-02-03 16:01 UTC, nmf2 requested changes
Códigos duplicados.

2022-02-03 16:01 UTC, nmf2 commented on src/utils/index.js
> +    const projectRoot = path.resolve(path.dirname(pkgInfo.path))
Acredito que esse código está duplicado, não dá pra usar a função de cima, `getProjectRootPath`, dentro dessa `listExtensionsPaths?` Se sim, como é simples, faz agora?

2022-02-03 16:01 UTC, nmf2 commented on src/commands/deploy.js
>    async inputVersionName () {
Essa função `getEntryPointFromUser` é basicamente a mesma coisa que é usada no publish (`getManifest`) e é parecida com o que é feito no select-extension, então cria uma task pra refatorar isso pra remover a duplicação de código.

Sobre esse código, apenas mudar a mensagem de 'Qual extensão deseja publicar ?' pra algo a ver com deploy é suficiente por agora. O resto faz na task q deve ser criada.

2022-02-03 17:27 UTC, luizAlbuquerqueJr commented on src/utils/index.js
> +    const projectRoot = path.resolve(path.dirname(pkgInfo.path))
done

2022-02-03 17:29 UTC, luizAlbuquerqueJr commented on src/commands/deploy.js
>    async inputVersionName () {
https://www.notion.so/beyondco/Refactor-no-Quoti-cLI-030f4e21ed4c4f2f9a22477d5e2cb54f

2022-02-03 18:17 UTC, nmf2 commented on src/commands/publish.js
> +          message: 'Qual extensão deseja realizar deploy ?',
```suggestion
          message: 'De qual extensão você deseja realizar deploy ?',
```

2022-02-03 18:20 UTC, nmf2 commented on src/utils/index.js
> +    const projectRoot = path.resolve(path.dirname(pkgInfo.path))
@luizAlbuquerqueJr, na verdade não está feito.

2022-02-04 15:28 UTC, nmf2 approved these changes
LGTM!

2022-02-04 15:28 UTC, merged