Feature/handle error
byndcloud/quoti-cli pull request #23
Opened 2022-02-07 14:57 UTC by luizAlbuquerqueJr

https://www.notion.so/beyondco/Tratamento-de-erros-na-CLI-do-QUOTI-01fb9cb4a63b490dbf8cfcb2aaaf5902

2022-02-08 12:13 UTC, nmf2 requested changes
Umas mudanças necessárias

2022-02-08 12:13 UTC, nmf2 commented on src/base.js
> +  }
@luizAlbuquerqueJr, no caso de erro com parse das flags o comando deveria, ser abortado, não?

2022-02-08 12:13 UTC, nmf2 commented on src/commands/download-current-version.js
> +    }
@luizAlbuquerqueJr, usa o `this.flags` nesse arquivo, por favor?

2022-02-08 17:29 UTC, luizAlbuquerqueJr commented on src/base.js
> +  }
try-catch desnecessário. Removi.

2022-02-08 17:29 UTC, luizAlbuquerqueJr commented on src/commands/download-current-version.js
> +    }
Done

2022-02-09 13:43 UTC, nmf2 approved these changes
LGTM!

2022-02-09 13:45 UTC, merged