Valida entry point
byndcloud/quoti-cli pull request #24
Opened 2022-02-07 16:25 UTC by luizAlbuquerqueJr

https://www.notion.so/beyondco/Checar-se-o-entrypoint-passado-pelo-usu-rio-realmente-de-uma-extens-o-775268730cdb42299d03cff9a14acdf3

2022-02-08 12:22 UTC, nmf2 requested changes
Possível melhoria em uma mensagem de erro

2022-02-08 12:22 UTC, nmf2 commented on src/utils/index.js
> +    )
@luizAlbuquerqueJr, acho que a mensagem fica melhor assim, o usuário não precisa, necessariamente, saber que as extensões que ele selecionou estão em `quoti.extensions`. Com essa mensagem, ele vai verificar o path ou vai fazer select-extension. O que tu acha?
```suggestion
    throw new Error(
      `O entrypoint especificado (${entryPointPath}) não está entre as extensões que já foram selecionadas. Tem certeza que o caminho está correto ou que a extensão já foi selecionada com qt select-extension?`
    )
```

2022-02-08 17:33 UTC, luizAlbuquerqueJr commented on src/utils/index.js
> +    )
done

2022-02-09 13:47 UTC, nmf2 approved these changes
LGTM!

2022-02-09 13:47 UTC, merged