Exibe versão remota durante publish/deploy
byndcloud/quoti-cli pull request #33
Opened 2022-03-04 22:31 UTC by luizAlbuquerqueJr

https://www.notion.so/beyondco/Mostrar-ao-usu-rio-qual-vers-o-atual-da-extens-o-na-hora-do-publish-deploy-c4ff32b62e5f4ba7a70ac3e8d78df000

2022-03-07 16:02 UTC, nmf2 requested changes

2022-03-07 16:02 UTC, nmf2 commented on src/commands/publish.js
> +        throw new Error(`Versão desejada ${this.flags.version} é menor que a versão atual ${lastVersion}`)
```suggestion
        throw new Error(`A versão desejada "${this.flags.version}" é menor ou igual à versão atual "${lastVersion}"`)
```

2022-03-07 16:02 UTC, nmf2 commented on src/commands/deploy.js
>            return true
@luizAlbuquerqueJr, já que vamos ter isso, faz com que o valor default pra resposta seja a versão atual mais um patch, de forma que se o cara possa só apertar "enter" e fazer deploy, não precise preencher a versão toda vez. Aí a mensagem da cli pode ser assim: 
Escolha uma nova versão para sua extensão (default: x.x.x+1), onde x.x.x é a versão atual (`lastVersion`) e x.x.x+1 é um patch na `lastVersion`.

Aproveita e bota isso no publish também, por favor?

2022-03-07 16:02 UTC, nmf2 commented on src/commands/publish.js
> +    this.logger.success(`Nova extensão publicada com sucesso. Versão ${version}`)
```suggestion
    this.logger.success(`Nova extensão publicada com sucesso: ${version}`)
```

2022-03-07 16:02 UTC, nmf2 commented on src/commands/publish.js
> +        'Nenhuma versão ativa para esta extensão. É necessário realizar publish de alguma versão antes de publicar'
@luizAlbuquerqueJr, acredito que esse log estava certo, não?

2022-03-08 01:56 UTC, nmf2 commented on src/commands/deploy.js
>            return true
Só registrando: decidimos não seguir com isso e ao invés disso, **remover a restrição de usar versionamento semântico.**

2022-03-08 19:13 UTC, luizAlbuquerqueJr commented on src/commands/publish.js
> +        throw new Error(`Versão desejada ${this.flags.version} é menor que a versão atual ${lastVersion}`)
Done

2022-03-08 19:22 UTC, luizAlbuquerqueJr commented on src/commands/deploy.js
>            return true
Done

2022-03-08 19:24 UTC, luizAlbuquerqueJr commented on src/commands/publish.js
> +    this.logger.success(`Nova extensão publicada com sucesso. Versão ${version}`)
Done

2022-03-08 19:26 UTC, luizAlbuquerqueJr commented on src/commands/publish.js
> +        'Nenhuma versão ativa para esta extensão. É necessário realizar publish de alguma versão antes de publicar'
Sim. Done

2022-03-08 21:10 UTC, nmf2 approved these changes
LGTM!

2022-03-08 21:10 UTC, merged