Corrigindo testes para o comando Serve
byndcloud/quoti-cli pull request #42
Opened 2022-03-14 22:30 UTC by luizAlbuquerqueJr

Não tem task

2022-03-15 13:47 UTC, nmf2 requested changes

2022-03-15 13:47 UTC, nmf2 commented on extensionsToTest/package.json
> +    "@google-cloud/storage": "^5.18.2",
@luizAlbuquerqueJr, não precisa disso, né? :thinking:

2022-03-15 16:52 UTC, luizAlbuquerqueJr commented on extensionsToTest/package.json
> +    "@google-cloud/storage": "^5.18.2",
nops

2022-03-15 17:14 UTC, luizAlbuquerqueJr commented on extensionsToTest/package.json
> +    "@google-cloud/storage": "^5.18.2",
done

2022-03-17 17:11 UTC, nmf2 approved these changes
LGTM!

2022-03-17 17:11 UTC, merged