Testando o comando qt serve com uma extensão sem build
byndcloud/quoti-cli pull request #43
Opened 2022-03-14 22:31 UTC by luizAlbuquerqueJr

https://www.notion.so/beyondco/Cria-teste-para-o-comando-serve-com-uma-extens-o-sem-build-1aaf58e1c3304e31ad51f92a8ae39f3c

2022-03-15 13:54 UTC, nmf2 commented on test/end-to-end/serve.test.js
> +    .stub(utils, 'getProjectRootPath', () => testProjectRootPath)
@luizAlbuquerqueJr, essa parte não é comum entre os dois tipos de setup de teste?

Seria possível criar uma variável `commonServeTestSetup` que contém isso e fazer os `setupServeTestNoBuild` e `setupServeTest` serem criados a partir de `commonServeTestSetup`?

2022-03-15 17:23 UTC, luizAlbuquerqueJr commented on test/end-to-end/serve.test.js
> +    .stub(utils, 'getProjectRootPath', () => testProjectRootPath)
Done. Só pra deixar claro. Eu vi que dava pra fazer isso porém achei que ia dá mais dor de cabeça e por isso deixei assim por enquanto.

2022-03-17 17:14 UTC, nmf2 requested changes
Melhoria de legibilidade

2022-03-17 17:14 UTC, nmf2 commented on test/end-to-end/serve.test.js
> +    const argsEmit = Socket.prototype.emit.args[0][0]
@luizAlbuquerqueJr, dá pra melhorar o entendimento disso, né?

2022-03-18 16:51 UTC, closed without merging