Adicionando o organização no manifest da extensão
byndcloud/quoti-cli pull request #53
Opened 2022-05-10 21:14 UTC by luizAlbuquerqueJr

https://www.notion.so/beyondco/poss-vel-fazer-deploy-de-extens-es-com-IDs-iguais-em-ORGs-diferentes-aa8df419de8e4cd886429f0b2214d39a

2022-05-11 21:14 UTC, nmf2 requested changes
Conversamos sobre os pontos com mais detalhes no Discord, apenas destacando para não esquecermos deles.

2022-05-11 21:14 UTC, nmf2 commented on src/config/credentials.js
> +}
Como conversamos no Discord, não devemos usar códigos de teste dentro de códigos da aplicação. Mudando para que o credentials path venha de uma env var resolve isso.

2022-05-11 21:14 UTC, nmf2 commented on test/end-to-end/common.test.js
> +    })
Aqui seria interessante usar o `forEach` para cada comando

2022-05-11 21:14 UTC, nmf2 commented on test/end-to-end/common.test.js
> +    }
Não precisa dessa callback quando ela não faz nada.

2022-05-11 21:14 UTC, nmf2 commented on test/services/credentials.js
> +  '/home/luizkof/Documentos/quoti/quoti-cli/test/beyondCredentials.json'
Não deixar esse path hard coded para tua máquina.

2022-05-11 22:04 UTC, luizAlbuquerqueJr commented on test/end-to-end/common.test.js
> +    }
resolvido na P.R https://github.com/byndcloud/quoti-cli/pull/53

2022-05-11 22:05 UTC, luizAlbuquerqueJr commented on test/end-to-end/common.test.js
> +    })
Resolvido na P.R https://github.com/byndcloud/quoti-cli/pull/53

2022-05-11 22:17 UTC, luizAlbuquerqueJr commented on src/config/credentials.js
> +}
done

2022-05-11 22:17 UTC, luizAlbuquerqueJr commented on test/services/credentials.js
> +  '/home/luizkof/Documentos/quoti/quoti-cli/test/beyondCredentials.json'
Sorry, passou batido

2022-05-12 17:52 UTC, nmf2 approved these changes
LGTM!

2022-05-12 17:52 UTC, merged