Separando setup e testes
byndcloud/quoti-cli pull request #54
Opened 2022-05-11 22:03 UTC by luizAlbuquerqueJr

https://www.notion.so/beyondco/Refatorando-os-testes-no-Quoti-cli-cebf98f4b7ae4649868657fe84594775

2022-05-12 18:01 UTC, nmf2 requested changes

2022-05-12 18:01 UTC, nmf2 commented on test/setups/deploySetup.js
> +    })
@luizAlbuquerqueJr, essa estrutura se repete 4 vezes nesse arquivo, seria possível generalizar de alguma forma?

2022-05-12 18:01 UTC, nmf2 commented on test/setups/serveSetup.js
> +      await delay(1000)
@luizAlbuquerqueJr, por que existe esse delay no fim do `do`?

2022-05-17 18:48 UTC, luizAlbuquerqueJr commented on test/setups/serveSetup.js
> +      await delay(1000)
isso é uma dívida técnica. Esse delay é necessário para que o comando qt serve se estabilize. Tempo de fazer o build... Irei corrigir em tasks futuras

2022-05-17 18:49 UTC, luizAlbuquerqueJr commented on test/setups/deploySetup.js
> +    })
Usei o register e ficou nota 10. https://www.npmjs.com/package/fancy-test Pesquise por "register"

2022-05-19 21:13 UTC, nmf2 commented on test/setups/serveSetup.js
> +      await delay(1000)
Okay

2022-05-24 17:05 UTC, nmf2 approved these changes
LGTM!

2022-05-24 17:05 UTC, merged