Adicionando paramsSerializer (axios) em ambiente de  produção
byndcloud/quoti-cli pull request #63
Opened 2022-06-27 16:30 UTC by luizAlbuquerqueJr

Sem task no Notion

2022-06-27 18:06 UTC, nmf2 approved these changes
LGTM!

2022-06-27 21:11 UTC, ovictoraurelio requested changes

2022-06-27 21:11 UTC, ovictoraurelio commented on src/config/axios.js
> +      config.baseURL = 'https://api.minhafaculdade.app/api/v1/'
```suggestion
      config.baseURL = 'https://api.quoti.cloud/api/v1/'
```

2022-06-27 22:16 UTC, nmf2 commented on src/config/axios.js
> +      config.baseURL = 'https://api.minhafaculdade.app/api/v1/'
![image](https://user-images.githubusercontent.com/15805140/176043730-abdc524f-a194-4a49-89b1-7b7d17c5531d.png)

2022-06-28 13:54 UTC, luizAlbuquerqueJr commented on src/config/axios.js
> +      config.baseURL = 'https://api.minhafaculdade.app/api/v1/'
entendido e feito

2022-06-28 13:58 UTC, nmf2 approved these changes
LGTM!

2022-06-28 13:58 UTC, merged