Criando databases pela CLI
byndcloud/quoti-cli pull request #68
Opened 2022-08-01 20:11 UTC by luizAlbuquerqueJr

https://www.notion.so/beyondco/008af63defd3494f97712b9ffc21ecd3?v=881eae7faf51481b8d47ce1d0d4440b7&p=7098f1d04cba482ca4ef341dcbc9efb4&pm=c

2022-09-01 21:09 UTC, luizAlbuquerqueJr commented
Devido a criação dos fieldTypes ENUM, float, double e boolean estou testando essa branch novamente e por isso movi para o estado de draft

2022-09-01 22:49 UTC, ovictoraurelio commented
Boa @luizAlbuquerqueJr! Valeu!

<img src="https://c.tenor.com/dQ5aJEcUyd4AAAAM/happy-birthday-month-elmo-potty.gif"/>

2022-09-02 13:45 UTC, luizAlbuquerqueJr commented
Essa P.R só irá funcionar em sua totalidade se as seguintes P.R forem fechadas
https://github.com/byndcloud/quoti-api/pull/388
https://github.com/byndcloud/quoti-api/pull/389
https://github.com/byndcloud/quoti-api/pull/390

2022-09-05 14:42 UTC, ovictoraurelio requested changes

2022-09-05 14:42 UTC, ovictoraurelio commented on src/services/database.js
> +    }
Acho importante incluir um log após o wait. Seria útil pois essas paradas vão acontecer assincronamente e possa ser que 1 falhe mas as demais dêem certo. O usuário sabendo quais deram certo e quais tiveram falha, com certeza, terá utilidade para a depender ele comentar uma e conseguir realizar com sucesso as demais.

" ✔️ Database {{name}} atualizado com sucesso "

2022-09-05 14:42 UTC, ovictoraurelio commented on src/services/database.js
> +    }
Em resumo a msm sugestão de cima...

" ✔️ Database {{name}} criado com sucesso "

2022-09-05 14:42 UTC, ovictoraurelio commented on src/commands/db/create.js
> +    'Cria todos os modelos presentes na pasta especificada pelo arg modelDirectory'
Não ficou claro pra mim o que isso fará.

2022-09-05 14:42 UTC, ovictoraurelio commented on src/commands/db/create.js
> +        'Endereço relativo a pasta ./src/pages onde será salvo sua extensão. Caso não exista a pasta ./src/pages o endereço fica relativo a raiz do projeto',
```suggestion
        'Endereço onde será salvo sua extensão. (Endereço relativo a pasta ./src/pages caso ./src/pages não exista o endereço fica relativo a raiz do projeto)',
```

2022-09-05 14:42 UTC, ovictoraurelio commented on src/commands/db/syncFieldTypes.js
> +  static description = 'Sincroniza os fieldTypes presentes na organização'
```suggestion
  static description = 'Sincroniza os tipos de campos disponíveis para databases presentes na organização'
```

2022-09-05 20:13 UTC, luizAlbuquerqueJr commented on src/services/database.js
> +    }
Fui tentar implementar oq vc falou e vi que é meio complicado pois teríamos que usar transactions na criação das views...
E acabei de lembrar que Nathan disse que o endpoint de criação dos databases devem ser feito em uma única transaction e se um único database falhar então faremos roolback de tudo. Portanto não sei como implementar essa feature que vc pediu

2022-09-05 20:15 UTC, luizAlbuquerqueJr commented on src/services/database.js
> +    }
Em resumo a msm resposta de cima

2022-09-05 20:22 UTC, luizAlbuquerqueJr commented on src/commands/db/create.js
> +    'Cria todos os modelos presentes na pasta especificada pelo arg modelDirectory'
quando escrevemos qt help db:create, a cli irá mostrar essa mensagem para o usuário. Também irá mostrar o argumento modelDirectory 
![image](https://user-images.githubusercontent.com/38214081/188509446-2622f16d-e89c-4c09-b88a-dd45b095e61d.png)

2022-09-05 20:25 UTC, luizAlbuquerqueJr commented on src/commands/db/create.js
> +        'Endereço relativo a pasta ./src/pages onde será salvo sua extensão. Caso não exista a pasta ./src/pages o endereço fica relativo a raiz do projeto',
Feito

2022-09-05 20:25 UTC, luizAlbuquerqueJr commented on src/commands/db/syncFieldTypes.js
> +  static description = 'Sincroniza os fieldTypes presentes na organização'
Feito

2022-09-05 23:32 UTC, luizAlbuquerqueJr commented on src/services/database.js
> +    }
Melhorei as mensagens de feedbacks no comando qt db:create. Porém foi necessário algumas mudanças na API.
https://github.com/byndcloud/quoti-api/pull/394

2022-09-06 20:31 UTC, ovictoraurelio approved these changes

2022-09-06 20:31 UTC, merged